### PR TITLE
Fixes allowing to compile against distro-supplied wxWidgets

### PR DESCRIPTION
**Pull request by KOLANICH**
Again, I haven't tested it on real games yet.

### CODE REVIEW

**Comment by hzdbyte** [comment]
Unfortunately some necessary fixes for wxWidgets don't allow us to use a generic distribution.

**Comment by KOLANICH** [comment]
These are worked around in this PR using dirty hacks (there is a lib circumventing `private`).

**Comment by hzdbyte** [comment]
It won't work properly without the current patch applied to the wxWidgets source tree.

**Comment by mirh** [comment]
If you are talking about `wxPatch.diff` it's not like it wouldn't need an update anyway. 
If I don't remove the animate/m_scale parts, it doesn't build on arch. 
I agree that trying to handle dependencies yourself is quite a sin.

**Comment by hzdbyte** [comment]
Looks like QSPGUI has to be reimplemented using another UI framework to fix this properly.
wxWidgets has some old issues (animations, html, aui, scrolling) fixed by wxPatch.diff that most likely will never be fixed in the main repo. Please feel free to reach out to me if you still want to contribute.

**Pull request closed without merging**
